#!/bin/sh
#
##
# System account
sudoPassword="qwer1234"
if type sw_vers >/dev/null 2>&1; then
    systemName=$(sw_vers | grep 'ProductName:' | awk '{print $2}')
else
    systemName="MacStudio"
fi
if type whoami >/dev/null 2>&1; then
    jenkinsUser=`whoami`
else
    jenkinsUser="jenkinsUser"
fi
#
##
# Shell Environment
if command -v android >/dev/null; then
    AOS_EXEC=$(command -v android)
    export ANDROID_HOME="$(dirname ${AOS_EXEC%android})"
else
    export ANDROID_HOME="/Users/${jenkinsUser}/Library/Android/sdk"
fi
#
##
# Git
if test -n "$(git config user.name)"; then
    GIT_USER=$(git config user.name)
else
    GIT_USER="AppDevTeam"
fi
if test -n "$(git config user.email)"; then
    GIT_EMAIL=$(git config user.email)
else
    GIT_EMAIL="app.support@company.com"
fi
#
##
# Teams
teamWebHook_debug="https://webhook.office.com/webhookb1/57dae0bf-abb2-43df-b7c1-73121c5a75a4@13a84ba8-5a74-4cdf-a639-57395cf71a8f/IncomingWebhook/abb12c1b7cb74044b535c2dfa5031729/a9b785d5-fbf6-4857-add7-dc64d1dd64c1"
teamWebHook="https://webhook.office.com/webhookb2/57dae0bf-abb2-43df-b7c1-73121c5a75a4@13a84ba8-5a74-4cdf-a639-57395cf71a8f/IncomingWebhook/abb12c1b7cb74044b535c2dfa5031729/a9b785d5-fbf6-4857-add7-dc64d1dd64c1"
#
##
# Web FrontEnd Point
frontEndPointUrl="https://macmini.company.com"
appRootPrefix="/Library/WebServer/Documents"
siteRepositoryUrl="https://github.com/neoroman/JenkinsAppDistTemplate.git"
#
##
# Variables Initialize
DEBUG_WORKSPACE_IOS="/Users/Company/Projects/app-ios"
DEBUG_WORKSPACE_ANDROID="/Users/Company/Projects/app-android"
SLACK="/usr/local/bin/slack"
SLACK_CHANNEL="#app-distribution"
APP_BUNDLE_IDENTIFIER_ANDROID="com.company.mobile"
OUTPUT_PREFIX="AppProject_"
USING_SCP=0
GIT=$(which git)
# for Android
Obfuscation_INPUT_FILE="Obfuscation_File.png"
outputGoogleStoreSuffix="-GoogleStore-release.apk"
outputOneStoreSuffix="-OneStore-release.apk"
# for iOS
INFO_PLIST="Projects/Info.plist"
OBFUSCATION_SOURCE=""
########
SCRIPT_NAME=$(basename $0)
DEBUGGING=0
PRODUCE_OUTPUT_USE=1 # Exit if output not using for distribution, maybe it's for SonarQube
OUTPUT_AND_EXIT_USE=0
USING_MAIL=0
WITH_TAG_PUSH=1
FOR_MASTER_BRANCH=0
FOR_ALL_BRANCH=0
FOR_SPECIFIC_BRANCH=0
PUSH_FORCE=0
CUSTOM_CONFIG=0
CUSTOM_LANG=0
USING_SCREENSHOT=1
USING_DSYM=0
USING_ADHOC_DEBUG=0
#
##
function getGitDomainFromUrl() {
    if [[ "${upstreamUrl#https://}" != "${upstreamUrl}" ]]; then
      upstreamProtocol="https://"
      tempUrl="${upstreamUrl#https://}"
    elif [[ "${upstreamUrl#http://}" != "${upstreamUrl}" ]]; then
      upstreamProtocol="http://"
      tempUrl="${upstreamUrl#http://}"
    fi
    if [[ "${tempUrl#*:*@}" != "${tempUrl}" ]]; then
      tempAccount="${tempUrl#*:*@}"
      upstreamAccount="${tempUrl#@${tempAccount}}"
      tempUrl="${tempUrl#*:*@}"
    else
      exit 1
    fi
    if [[ "${tempUrl%%/*}" != "${tempUrl}" ]]; then
      upstreamDomain="${tempUrl%%/*}"
    fi
}
