#!/bin/sh
##
HOSTNAME=$(hostname)
CURRENT=$PWD
A2PS="/usr/local/bin/a2ps"
if [ ! -f $A2PS ]; then
  cd /usr/local/bin
  if test -n "$sudoPassword"; then
    if [[ "$sudoPassword" != "qwer1234" ]]; then
      sudo -S -k ln -s `which a2ps` <<<"${sudoPassword}"
    fi
  fi
  cd $CURRENT
fi
GS="/usr/local/bin/gs"
if [ ! -f $GS ]; then
  cd /usr/local/bin
  if test -n "$sudoPassword"; then
    if [[ "$sudoPassword" != "qwer1234" ]]; then
      sudo -S -k ln -s `which gs` <<<"${sudoPassword}"
    fi
  fi
  cd $CURRENT
fi
CONVERT="/usr/local/bin/convert"
if [ ! -f $CONVERT ]; then
  cd /usr/local/bin
  if test -n "$sudoPassword"; then
    if [[ "$sudoPassword" != "qwer1234" ]]; then
      sudo -S -k ln -s `which convert` <<<"${sudoPassword}"
    fi
  fi
  cd $CURRENT
fi
if type curl >/dev/null 2>&1; then
  CURL=`which curl`
else
  CURL="/usr/bin/curl"
fi
USING_JSON=1
###################
if test -z "${INPUT_OS}"; then
    $SCRIPT_NAME -h
    exit
fi
if [ $DEBUGGING -eq 1 ]; then
  if test -z $WORKSPACE; then
    if [[ "$INPUT_OS" == "ios" ]]; then
      WORKSPACE=$DEBUG_WORKSPACE_IOS
    elif [[ "$INPUT_OS" == "android" ]]; then
      WORKSPACE=$DEBUG_WORKSPACE_ANDROID
    else
      WORKSPACE="."
    fi
  fi
elif test -z $WORKSPACE; then
  WORKSPACE="."
fi
###################
if test -z $IS_RELEASE; then
  if [ -d ".git" ]; then
    GIT_LAST_TAG=$(cd $WORKSPACE && $GIT describe --tags)
    if [[ $GIT_LAST_TAG == R* ]]; then
      IS_RELEASE=1
      RELEASE_TYPE="release"
    else
      IS_RELEASE=0
      RELEASE_TYPE="develop"
    fi
  fi
fi
###################
FILE_TODAY=$(/bin/date "+%y%m%d")
###################